version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bankcards-db
    restart: always
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcards-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankcards
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/migration/changelog-master.xml
      JWT_SECRET: SuperSecretJWTKeyChangeMe123
    ports:
      - "8080:8080"

volumes:
  pgdata: